from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def _hit_rate(ret_block: dict, key: str) -> float | None:
    b = ret_block.get(key)
    if not isinstance(b, dict):
        return None
    h = b.get("hits")
    t = b.get("totals")
    if h is None or t is None:
        return None
    ti = int(t)
    if ti <= 0:
        return None
    return float(h) / float(ti)


def _load_pair(run_dir: Path) -> tuple[dict, dict] | None:
    mp = run_dir / "metrics.json"
    cp = run_dir / "config.json"
    if not mp.is_file():
        return None
    metrics = json.loads(mp.read_text(encoding="utf-8"))
    config: dict = {}
    if cp.is_file():
        config = json.loads(cp.read_text(encoding="utf-8"))
    return metrics, config


def _latex_escape_id(name: str) -> str:
    return name.replace("_", r"\_")


def _fmt4(x: object) -> str:
    if x is None:
        return "---"
    if isinstance(x, (int, float)):
        return "%.3f" % float(x)
    return str(x)


def main() -> None:
    p = argparse.ArgumentParser(
        description="Aggregate metrics.json (+ config.json) under rubert_runs/*/ into CSV and LaTeX rows.",
    )
    p.add_argument(
        "--root",
        type=Path,
        default=Path("rubert_runs"),
        help="Directory containing run subfolders",
    )
    p.add_argument(
        "--csv-out",
        type=Path,
        default=Path("artifacts/summary.csv"),
    )
    p.add_argument(
        "--latex-out",
        type=Path,
        default=Path("coursework-latex/lyrata-kurs/tables/results_generated.tex"),
    )
    p.add_argument(
        "--main-protocol-only",
        action="store_true",
        help="Filter leave_games_out, top_percent=35, held_out_games_seed=17, skip local_* and run_020_top_percent_50_diag",
    )
    args = p.parse_args()
    root: Path = args.root.expanduser().resolve()
    rows: list[dict[str, object]] = []
    if not root.is_dir():
        print("root missing or not a directory", root)
        return
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        pair = _load_pair(child)
        if pair is None:
            continue
        metrics, config = pair
        name = child.name
        script = str(metrics.get("script") or config.get("script") or "")
        split = str(config.get("split") or "")
        top_p = config.get("top_percent")
        ho_seed = config.get("held_out_games_seed")
        seed = config.get("seed")
        ret = metrics.get("retrieval")
        tm = metrics.get("test_metrics") or {}
        if not isinstance(ret, dict):
            ret = {}
        row: dict[str, object] = {
            "run_id": name,
            "script": script,
            "split": split,
            "top_percent": top_p,
            "held_out_games_seed": ho_seed,
            "seed": seed,
            "test_mae_macro": tm.get("mae_macro"),
            "test_rmse_macro": tm.get("rmse_macro"),
            "test_column_pearson_mean": tm.get("column_pearson_mean"),
            "test_row_cosine_mean": tm.get("row_cosine_mean"),
            "test_r2_pooled": tm.get("r2_pooled"),
            "retrieval_cosine_hit_rate": _hit_rate(ret, "cosine"),
            "retrieval_rmse_hit_rate": _hit_rate(ret, "rmse"),
            "retrieval_mae_hit_rate": _hit_rate(ret, "mae"),
            "epochs_ran": metrics.get("epochs_ran"),
        }
        if args.main_protocol_only:
            if name.startswith("local_"):
                continue
            if name == "run_020_top_percent_50_diag":
                continue
            if split != "leave_games_out":
                continue
            if ho_seed is not None and int(ho_seed) != 17:
                continue
            if top_p is None or abs(float(top_p) - 35.0) > 1e-6:
                continue
        rows.append(row)

    rows.sort(
        key=lambda r: (
            float(r["retrieval_cosine_hit_rate"] or -1.0),
            float(r["test_column_pearson_mean"] or -1.0),
        ),
        reverse=True,
    )
    args.csv_out.parent.mkdir(parents=True, exist_ok=True)
    if rows:
        keys = list(rows[0].keys())
        with args.csv_out.open("w", encoding="utf-8", newline="") as f:
            w = csv.DictWriter(f, fieldnames=keys)
            w.writeheader()
            for r in rows:
                w.writerow(r)
    args.latex_out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% auto-generated by scripts/aggregate_run_metrics.py (aggregate_rubert_run_metrics.py)",
        "% do not edit by hand; re-run the script after new runs",
        r"\begin{tabular}{|l|l|r|r|r|r|r|r|}",
        r"\hline",
        r"прогон & семейство & MAE & $\overline{\rho}$ & cos hit & RMSE hit & MAE hit & эп. \\",
        r"\hline",
    ]
    for r in rows:
        if args.main_protocol_only:
            if r.get("retrieval_cosine_hit_rate") is None:
                continue
        rid = _latex_escape_id(str(r["run_id"]))
        sc = str(r["script"])
        if sc:
            sc = _latex_escape_id(sc)
        mae = r.get("test_mae_macro")
        rho = r.get("test_column_pearson_mean")
        ch = r.get("retrieval_cosine_hit_rate")
        rh = r.get("retrieval_rmse_hit_rate")
        mh = r.get("retrieval_mae_hit_rate")
        ep = r.get("epochs_ran")
        line = " & ".join(
            [
                "\\texttt{%s}" % rid,
                sc,
                _fmt4(mae),
                _fmt4(rho),
                _fmt4(ch),
                _fmt4(rh),
                _fmt4(mh),
                str(ep) if ep is not None else "---",
            ]
        )
        lines.append(line + r" \\")
    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    args.latex_out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", args.csv_out, "rows", len(rows))
    print("wrote", args.latex_out)


if __name__ == "__main__":
    main()
