TEXT_MUSICS_RUBERT_TABLE = "text_musics_rubert"
SOURCE_TABLE = "text_musics_rel"

TEXT_MUSIC_TRAIN_EXPERIMENTS_TABLE = "text_music_train_experiments"

CREATE_TEXT_MUSIC_TRAIN_EXPERIMENTS_SQL = f"""
create table if not exists {TEXT_MUSIC_TRAIN_EXPERIMENTS_TABLE} (
    id bigserial primary key,
    created_at timestamptz not null default now(),
    script text not null,
    argv_text text not null,
    config_json jsonb not null,
    embedding_column text not null,
    rubert_table text not null,
    music_table text not null,
    y_group text not null,
    split_mode text not null,
    merge_identical_embeddings boolean not null default false,
    test_fraction double precision,
    test_games integer,
    seed integer not null,
    n_rows_loaded integer not null,
    n_y_columns integer not null,
    n_train_fit integer not null,
    n_val integer not null,
    n_test integer not null,
    val_tune_fraction double precision,
    top_percent double precision,
    linear_model text,
    linear_alpha double precision,
    linear_sweep_models text,
    linear_refit_best_on_train_plus_val boolean,
    linear_final_fit_wall_s double precision,
    mlp_hidden text,
    mlp_dropout double precision,
    mlp_lr double precision,
    mlp_weight_decay double precision,
    mlp_epochs_ran integer,
    mlp_batch_size integer,
    mlp_patience integer,
    mlp_standardize_x boolean,
    mlp_standardize_y boolean,
    mlp_best_val_mae_norm_macro double precision,
    mlp_train_wall_s double precision,
    train_mae_macro double precision,
    train_rmse_macro double precision,
    train_r2_macro double precision,
    train_evs_macro double precision,
    train_medae_macro double precision,
    train_row_cosine_mean double precision,
    train_column_pearson_mean double precision,
    train_max_abs_macro double precision,
    val_mae_macro double precision,
    val_rmse_macro double precision,
    val_r2_macro double precision,
    val_evs_macro double precision,
    val_medae_macro double precision,
    val_row_cosine_mean double precision,
    val_column_pearson_mean double precision,
    val_max_abs_macro double precision,
    test_mae_macro double precision,
    test_rmse_macro double precision,
    test_r2_macro double precision,
    test_evs_macro double precision,
    test_medae_macro double precision,
    test_row_cosine_mean double precision,
    test_column_pearson_mean double precision,
    test_max_abs_macro double precision,
    retrieval_top_percent double precision,
    retrieval_rmse_hit_rate double precision,
    retrieval_mae_hit_rate double precision,
    retrieval_cosine_hit_rate double precision,
    retrieval_rmse_hits integer,
    retrieval_rmse_total integer,
    retrieval_mae_hits integer,
    retrieval_mae_total integer,
    retrieval_cosine_hits integer,
    retrieval_cosine_total integer,
    retrieval_skipped integer
);
"""

CREATE_TEXT_MUSICS_RUBERT_SQL = f"""
create table if not exists {TEXT_MUSICS_RUBERT_TABLE} (
    game text not null,
    phrase_order integer not null,
    text1 text,
    text_analized real[],
    music integer references music_data(id),
    primary key (game, phrase_order)
);
"""
